version: '3.8'

services:
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE=railway
  #     - DATABASE_USER=postgres
  #     - DATABASE_PASSWORD=BA1CA41E6B3f6*FD5E-2FdGGAEcFecg*
  #     - DATABASE_HOST=postgres
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: railway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BA1CA41E6B3f6*FD5E-2FdGGAEcFecg*
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
