version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
    command: ["wait-for-it", "postgres:5432", "--", "npm", "run", "up"]

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: railway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BA1CA41E6B3f6*FD5E-2FdGGAEcFecg*
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
